[build]
publish = "dist/"
command = "yarn build"

[context.production.environment]
VITE_MULTINET_HOST = "https://api.multinet.app"
VITE_OAUTH_API_ROOT = "https://api.multinet.app/oauth/"
VITE_OAUTH_CLIENT_ID = "FKSbPC4GNN31E3a6s6f4Uo96gfNfKcGGcEH3K4vq"

[context.deploy-preview.environment]
VITE_MULTINET_HOST = "https://api.multinet.app"
VITE_OAUTH_API_ROOT = "https://api.multinet.app/oauth/"
VITE_OAUTH_CLIENT_ID = "FKSbPC4GNN31E3a6s6f4Uo96gfNfKcGGcEH3K4vq"
