name: CI

on: 
  pull_request:
    branches:
    - master
  
  push:
    branches:
    - master

jobs:
  build-and-test:
    name: Build and test on Ubuntu - Node 10
    runs-on: ubuntu-latest
    steps:
    - run: git clone https://github.com/multinet-app/multinet.git
    - run: cd multinet && pwd

    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: pip install pipenv
    - run: cd multinet && pipenv install
    - run: cd multinet && pipenv run serve &

    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn serve & sleep 1
    - run: yarn test
    
