name: CI

on: 
  pull_request:
    branches:
    - master
  
  push:
    branches:
    - master

jobs:
  build-and-test:
    name: Build and test on Ubuntu - Node 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
    
